# Generated by Django 3.2 on 2021-06-27 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minatech', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='courseContent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.FileField(upload_to='')),
                ('title', models.CharField(max_length=1000)),
                ('notes', models.TextField()),
                ('uploadedOn', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minatech.courses')),
            ],
        ),
    ]
