# Generated by Django 3.2 on 2021-06-27 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minatech', '0002_coursecontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecontent',
            name='content',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='coursecontent',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
